### ISSUE TITLE
GPU in Docker

### ISSUE THREAD

**Issue by celevra** [sublime-security/sublime-platform#188]
Hi,

what are the steps to enable cuda/gpu accelaration for hydra in a docker deployment?
a simple:
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

seems not enough.
for use a hosting on a cloud provider like MS, google or AWS is no option.

regards
